rm -rf dist/es5
rm -rf automocks
rm -rf listener
rm -rf mocks

# compile
tsc

# create path shortcuts
prelude='/** This file has been auto-generated by build scripts. */'
mkdir automocks
echo "$prelude"'
export * from "../dist/es5/exports/automocks"' > automocks/index.d.ts
echo "$prelude"'
export * from "../dist/es5/exports/automocks.js"' > automocks/index.js

mkdir mocks
echo "$prelude"'
export * from "../dist/es5/exports/mocks"' > mocks/index.d.ts
echo "$prelude"'
export * from "../dist/es5/exports/mocks.js"' > mocks/index.js

mkdir listener
echo "$prelude"'
import defaultVal from "../dist/es5/exports/listener";
export default defaultVal;
export * from "../dist/es5/exports/listener";' > listener/index.d.ts
echo "$prelude"'
import defaultVal from "../dist/es5/exports/listener.js";
export default defaultVal;
export * from "../dist/es5/exports/listener.js";' > listener/index.js
